[[host]]
address = "localhost"
base_port = 8000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 9000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 10000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 11000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 12000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 13000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 14000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 15000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 16000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}

[[host]]
address = "localhost"
base_port = 17000
num_cores = 1
ssh = { username = "antonelloamore", key_file = "/Users/antonelloamore/.ssh/biol525D"}
