version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "test"
      include: "scope"
  - package-ecosystem: cargo
    directory: "/fuzz"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "test(fuzz)"
      include: "scope"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"